youbot:
  arm_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 100.0, d: 10.0}
  arm_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 100.0, d: 10.0}
  arm_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 100.0, d: 10.0}
  arm_4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 100.0, d: 10.0}
  arm_5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 100.0, d: 10.0}
  finger_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_left_joint
    pid: {p: 100.0, d: 10.0}
  finger_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_right_joint
    pid: {p: 100.0, d: 10.0}
